version: '2'

services:
  mongo:
    container_name: mongo
    build: 
      context: ./app/dockerfiles/mongo/
    volumes:
      - /data/db/:/data/db/
    ports:
      - "27017:27017"
    networks:
      network:
        ipv4_address: 10.0.1.2

  app:
    container_name: app
    build: 
      context: ./
      dockerfile: ./app/dockerfiles/app/Dockerfile
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      network:
        ipv4_address: 10.0.1.3

networks:
  network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.1.0/24
