version: '2'

services:
  mongo:
    container_name: mongo
    build: 
      context: ./mongo/
    volumes:
      - /data/db/:/data/db/
    ports:
      - "27017:27017"
    networks:
      chatNet:
        ipv4_address: 10.0.1.2

networks:
  chatNet:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.1.0/24