export const AUDIO_CONTEXT_INIT = 'AUDIO_CONTEXT_INIT';
export const GAIN_NODE_VALUES = 'GAIN_NODE_VALUES';
export const DISTORTION_VALUES = 'DISTORTION_VALUES';
export const FILTER_NODE_VALUES = 'FILTER_NODE_VALUES';
export const INPUT_STREAM_VALUE = 'INPUT_STREAM_VALUE';
export const ADD_NODE = 'ADD_NODE';
export const REMOVE_NODE = 'REMOVE_NODE';
