export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REDIRECT_TO_LOGIN = 'REDIRECT_TO_LOGIN';
export const REDIRECT_TO_REGISTER = 'REDIRECT_TO_REGISTER';
export const SAVE_TOKEN = 'SAVE_TOKEN';